### ISSUE TITLE
Warning generate compiling program

### ISSUE THREAD

**Issue by gagl2155** [zaneobrien/OBrien_Zane-CSCI-2270-Final-Project#2]
This is generated when compiling the program on Mac OSX 10.10:

```
$ g++ -std=c++11 MovieSeller.cpp main.cpp -o main
MovieSeller.cpp:91:13: warning: expression result unused [-Wunused-value]
        for(it; it != hashTable[index].end(); it++)
            ^~
1 warning generated.
```

I can do a pull request and fix this pretty quickly.

**Comment by gagl2155** [comment]
Warning fixed in pull request submitted

**Comment by zaneobrien** [comment]
I accepted the pull request, Thanks! do you know why it was generating this warning?

**Comment by gagl2155** [comment]
Since the iterator was was already set on the line above the for loop, the first condition is fulfilled, so you can just leave it blank. I think the warning was generated because it either expects something to be set in the first condition or it expects it to be blank. An example:

```
int i = 0;
for (; i < 10; i++) {}
```

is equivalent to

```
for (int i = 0; i < 10; i++) {}
```

**Comment by zaneobrien** [comment]
Oh I see, its just that the iterator was declared before the loop.
